sudo: required

language: ruby

services:
  - docker

script:
  - docker build -f Dockerfile -t pipenv-install-pyspark:0.1 .
  - docker run -w /tmp pipenv-install-pyspark:0.1 pipenv install --verbose
